spring:
  profiles:
    active: dev
  application:
    name: test

---
spring:
  config:
    activate:
      on-profile: dev
    import: classpath:application-dev.yml

---
spring:
  config:
    activate:
      on-profile: prod
    import: classpath:application-prod.yml